### ISSUE TITLE
 raise ValueError(

### ISSUE THREAD

**Issue by zhang402115** [eduardopietre/PyMp4ToPdf#1]
raise ValueError(
ValueError: win_size exceeds image extent. Either ensure that your images are at least 7x7; or pass win_size explicitly in the function call, with an odd value less than or equal to the smaller side of your images. If your images are multichannel (with color channels), set channel_axis to the axis number corresponding to the channels.

**Comment by Jaffen1-umbc** [comment]
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "C:\Users\PC\Documents\PyMp4ToPdf\mp4_to_pdf_gui.py", line 32, in run
    self.convert()
  File "C:\Users\PC\Documents\PyMp4ToPdf\mp4_to_pdf_gui.py", line 99, in convert
    changes = self.structural_similarity_filter(diff_pairs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Documents\PyMp4ToPdf\mp4_to_pdf_gui.py", line 82, in structural_similarity_filter
    ssim = structural_similarity(p[0], p[1], multichannel=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\skimage\metrics\_structural_similarity.py", line 186, in structural_similarity
    raise ValueError(
ValueError: win_size exceeds image extent. Either ensure that your images are at least 7x7; or pass win_size explicitly in the function call, with an odd value less than or equal to the smaller side of your images. If your images are multichannel (with color channels), set channel_axis to the axis number corresponding to the channels.

**Comment by eduardopietre** [comment]
Thanks, should be fixed.

The issue was a change in the scikit-image API. structural_similarity was still called with multichannel=True, which no longer marks the RGB axis; the library now expects channel_axis. Without that, color frames of shape (height, width, 3) were treated as 3D volumes, the default 7-pixel window was larger than the 3-channel axis, and conversion failed with win_size exceeds image extent. Both mp4_to_pdf.py and mp4_to_pdf_gui.py now pass channel_axis=-1, so SSIM runs per color channel as intended.
